# Generated by Django 3.0.7 on 2020-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpixel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
