# Generated by Django 3.0.7 on 2020-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpixel', '0002_auto_20200717_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
