# Generated by Django 3.0.7 on 2020-07-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtpixel', '0003_auto_20200717_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='title',
        ),
    ]
