# Generated by Django 3.0.7 on 2020-07-31 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wtpixel', '0006_accountmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
