# Generated by Django 3.0.7 on 2020-10-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtpixel', '0010_auto_20201006_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
    ]
