# Generated by Django 3.0.7 on 2020-10-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtpixel', '0013_auto_20201006_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
