# Generated by Django 3.1.2 on 2020-10-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtpixel', '0016_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
